#!/usr/bin/env python3

// def py

pipeline {
    agent any
    parameters {
        choice(name: 'JobType', choices: ['QXMgr', 'QXOne', 'QXSecond'], description: '')
        string(name: 'ExistingSchedule', defaultValue: '', description: '')
	    string(name: 'NewSchedule', defaultValue: '', description: '')
    }
    stages {
        stage("init") {
            steps {
                script {
                   git branch: 'main', credentialsId: 'git-credentials', url: 'https://github.com/Pratyush3997/python-jenkins.git'
                }
            }
        }    
        stage("change") {
            steps {
                script {
                   sh '''
                        echo ${ExistingSchedule}
                        python3 main.py -u Admin -p 11f9898624c4709f4c9b3fb7efa23db5e8 ${ExistingSchedule} ${NewSchedule} ${JobType}
                      '''
                }
            }
        }       
    }
}
