#!/usr/bin/env python

def py

pipeline {
    agent any
    parameters {
        choice(name: 'JobType', choices: 'QXMgr', 'QXOne', 'QXSecond'], description: '')
        booleanParam(name: 'ExistingSchedule', defaultValue: '', description: '')
	booleanParam(name: 'NewSchedule', defaultValue: '', description: '')
    }
    stages {
        stage("init") {
            steps {
                script {
                   echo"testing"
                }
            }
        }           
    }
}
